name: Deploy Changed Files to Salesforce

on:
  push:
    branches: [main]
    paths:
      - 'force-app/main/default/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Write JWT private key
        run: echo "${{ secrets.SF_PRIVATE_KEY }}" > jwt.key

      - name: Authenticate with Salesforce
        run: |
          sf org login jwt \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --username ${{ secrets.SF_USERNAME }} \
            --jwt-key-file jwt.key

      - name: Get changed files
        run: git diff --name-only HEAD~1 > changed_files.txt || echo "No changes"

      - name: Deploy changed metadata
        run: |
          mkdir changed
          while IFS= read -r file; do
            if [[ -f "$file" ]]; then
              dir=$(dirname "$file")
              cp -R "$dir" changed/
            fi
          done < changed_files.txt
          sf project deploy start --source-dir changed --target-org ${{ secrets.SF_USERNAME }}

      - name: Logout
        run: sf org logout --target-org ${{ secrets.SF_USERNAME }} --no-prompt

      - name: Success message
        run: echo "✅ Deployment to Salesforce completed!"
